
tasks:
  - name: Setup Rocker Containers
    init: UID=$(UID) docker-compose -f dockerfiles/rstudio-docker-compose.yml -f dockerfiles/jupyter-docker-compose.yml pull
  - name: Install Nextflow
    command: |
      curl -s https://get.nextflow.io | bash
      sudo mv nextflow /usr/local/bin
  - name: Install Quarto
    command: |
      wget https://quarto.org/download/latest/quarto-linux-amd64.deb
      sudo apt-get install r-base r-base-dev
      sudo dpkg -i quarto-linux-amd64.deb
      rm quarto-linux-amd64.deb
      quarto check all

ports:
  # Expose port for RStudio
  - port: 8787
    onOpen: open-browser
# Expose port for Jupyter
  - port: 8888
    onOpen: open-browser

vscode:
  extensions:
    - ritwickdey.liveserver
    - quarto.quarto
