project:
  type: book

book:
  title: "Reproducible Research"
  author: "Mahesh Binzer-Panchal"
  date: last-modified
  page-navigation: true
  sidebar:
    title: "Content:"
    search: true
  chapters:
    - index.qmd
    - intro.qmd
    - docs.qmd
    - part: data_management/intro.qmd
      chapters:
        - data_management/layout.qmd
    - part: conda/intro.qmd
      chapters:
        - conda/environments.qmd
    - part: docker/intro.qmd
    - part: apptainer/intro.qmd
    - part: nextflow/intro.qmd
      chapters:
        - nextflow/basics.qmd
        - nextflow/processes.qmd
        - nextflow/staging.qmd
        - nextflow/async.qmd
        - nextflow/operators.qmd
        - nextflow/config.qmd
        - nextflow/convert.qmd
        - nextflow/nfcore.qmd
    - part: quarto/intro.qmd
      chapters: 
        - quarto/markdown.qmd
        - quarto/input.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: sandstone
  # pdf:
  #   documentclass: scrreprt



